// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bubetfgnlzedywxlkoec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1YmV0ZmdubHplZHl3eGxrb2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzAxNDMsImV4cCI6MjA2MTYwNjE0M30.BNqcEX_vNx6jz61JlB-aPaZ_THN5IgIdnFX4qHJFQ1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);